### PR TITLE
DB Update

### PR DESCRIPTION
**Pull request by CooperStansbury**
PR includes updated DDL statements and metadata descriptors, updated data dictionary, repo organization, ect... 

Important Notes:

1. `order.Order_Date` is a MySQL Datetime field now. 
1. `customer.Password' was added and populated.
1. `order.Product_Retail_Price` changed to `order.Order_Total`. 
1. `customer.Customer_ID` and `order.Order_ID` are auto-increment now.
1. `customer.State` and `shipping_costs.State_Code` are `Varchar(3)` instead of `Text`.
1. The only formally declared FK are from `order.Product_ID` and `order.Customer_ID`.

### CODE REVIEW

**Comment by KendraMBach** [comment]
This looks great. Just to clarify, we will want to run each .sql file for each of the tables, and then import the corresponding data from the proper .csv, right?

**Comment by KendraMBach** [comment]
I can work with this for sure. Just let me know when you're ready for the merge.

**Comment by CooperStansbury** [comment]
Fire at will.

**Review by KendraMBach — APPROVED** [review]
None of these changes - or those in previous commits - are going to hinder my progress or cause unwanted issues (that I can see) at this time. I would like to merge this now and begin working with the updated tables.

**Pull request merged**
