### PR TITLE
Refinements and integrations

### PR DESCRIPTION
**Pull request by KendraMBach**
PR for receipt and newsletter functionality plus minor updates to index (aesthetics and url updates for product highlights section). 
Will squash commits to cleanup history upon approval of PR.

### CODE REVIEW

**Comment by mferrall** [comment]
I haven't been able to get the emails to run, but I think it might be due to the particulars of how my machine is set up.  I'm gonna try again tomorrow.

**Comment by KendraMBach** [comment]
@mferrall - Yes and no. This is how my local is setup, which doesn't necessarily mean it's how yours is. If you already have a version of python3 setup elsewhere, then you can just change the python path for that particular file for your local (as in, do not include the change in any commit/do not push the change to master).
But if you do not have python3 setup, then feel free to get anaconda (just note, it's not recommended for all tasks - @CooperStansbury can attest to this).

As a side note, you will not be able to get the .py scripts running right away. I will need to merge this PR to apply the bug fix for one of the scripts. After I do this and you pull/rebase with master, then make sure you can get the .py scripts running via command line. If you run into errors with this, ensure you have python3 installed in some way, along with MySQL-connector for python (pip install MySQL-connector-python). If that still causes errors, let me or @CooperStansbury know. 

Hope this helps.

**Comment by CooperStansbury** [comment]
@KendraMBach looks good. Merging.

**Comment by mferrall** [comment]
> @mferrall - Yes and no. This is how my local is setup, which doesn't necessarily mean it's how yours is. If you already have a version of python3 setup elsewhere, then you can just change the python path for that particular file for your local (as in, do not include the change in any commit/do not push the change to master).
> But if you do not have python3 setup, then feel free to get anaconda (just note, it's not recommended for all tasks - @CooperStansbury can attest to this).
> 
> As a side note, you will not be able to get the .py scripts running right away. I will need to merge this PR to apply the bug fix for one of the scripts. After I do this and you pull/rebase with master, then make sure you can get the .py scripts running via command line. If you run into errors with this, ensure you have python3 installed in some way, along with MySQL-connector for python (pip install MySQL-connector-python). If that still causes errors, let me or @CooperStansbury know.
> 
> Hope this helps.

Yes that's helpful, I'll try again tonight.

**Pull request merged**
